### PR TITLE
Handle invalid icon urls

### LINKED ISSUE #61: Popup is empty
I just installed, see screenshot:
2016-09-08 13_16_30-acr_ kompatibilitat von add-ons mit multiprozess-firefox melden - firefox develo

Current Firefox Developer Edition. Here's the troubleshooting information:

```
{
  "application": {
    "name": "Firefox",
    "osVersion": "Windows_NT 6.3",
    "version": "50.0a2",
    "buildID": "20160908004007",
    "userAgent": "Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:50.0) Gecko/20100101 Firefox/50.0",
    "safeMode": false,
    "updateChannel": "aurora",
    "supportURL": "https://support.mozilla.org/1/firefox/50.0a2/WINNT/en-US/",
    "numTotalWindows": 1,
    "numRemoteWindows": 1,
    "remoteAutoStart": true,
    "autoStartStatus": 0
  },
  "modifiedPreferences": {
    "accessibility.typeaheadfind.flashBar": 0,
    "browser.cache.disk.smart_size.first_run": false,
    "browser.cache.disk.capacity": 358400,
    "browser.cache.disk.hashstats_reported": 1,
    "browser.cache.disk.filesystem_reported": 1,
    "browser.cache.frecency_experiment": 1,
    "browser.cache.disk.smart_size.use_old_max": false,
    "browser.download.importedFromSqlite": true,
    "browser.places.smartBookmarksVersion": 8,
    "browser.search.useDBForOrder": true,
    "browser.sessionstore.upgradeBackup.latestBuildID": "20160908004007",
    "browser.startup.homepage_override.mstone": "50.0a2",
    "browser.startup.homepage": "https://google.de/",
    "browser.startup.homepage_override.buildID": "20160908004007",
    "browser.tabs.warnOnClose": false,
    "browser.tabs.remote.autostart.2": false,
    "browser.tabs.remote.autostart": true,
    "browser.urlbar.suggest.searches": true,
    "browser.urlbar.userMadeSearchSuggestionsChoice": true,
    "dom.apps.lastUpdate.buildID": "20160725004033",
    "dom.w3c_touch_events.enabled": 1,
    "dom.push.userAgentID": "2696fb230c4c4ee6ad5aeef72544611b",
    "dom.apps.reset-permissions": true,
    "dom.apps.lastUpdate.mstone": "49.0a2",
    "extensions.lastAppVersion": "50.0a2",
    "font.internaluseonly.changed": false,
    "gfx.crash-guard.status.": 2,
    "gfx.crash-guard.d3d11layers.appVersion": "50.0a2",
    "gfx.crash-guard.d3d11layers.driverVersion": "13.251.9001.1001",
    "gfx.crash-guard.d3d11layers.deviceID": "0x6778",
    "gfx.crash-guard.d3d11layers.feature-d3d11": true,
    "gfx.crash-guard.status.d3d11video": 2,
    "gfx.crash-guard.d3d11layers.feature-d2d": true,
    "gfx.crash-guard.status.d3d11layers": 2,
    "gfx.crash-guard.status.d3d9video": 2,
    "keyword.URL": true,
    "media.gmp-eme-adobe.lastUpdate": 1472031820,
    "media.gmp-widevinecdm.lastUpdate": 1472031822,
    "media.gmp-gmpopenh264.lastUpdate": 1472031821,
    "media.benchmark.vp9.versioncheck": 1,
    "media.gmp-eme-adobe.abi": "x86_64-msvc-x64",
    "media.hardware-video-decoding.failed": false,
    "media.gmp-gmpopenh264.version": "1.6",
    "media.gmp-manager.lastCheck": 1473333182,
    "media.gmp-widevinecdm.version": "1.4.8.903",
    "media.gmp-eme-adobe.version": "17",
    "media.gmp.storage.version.observed": 1,
    "media.benchmark.vp9.fps": 201,
    "media.gmp-widevinecdm.abi": "x86_64-msvc-x64",
    "media.gmp-gmpopenh264.abi": "x86_64-msvc-x64",
    "media.gmp-manager.buildID": "20160908004007",
    "network.prefetch-next": false,
    "network.dns.disablePrefetch": true,
    "network.http.speculative-parallel-limit": 0,
    "network.predictor.cleaned-up": true,
    "network.cookie.prefsMigrated": true,
    "places.history.expiration.transient_current_max_pages": 106998,
    "places.database.lastMaintenance": 1473154218,
    "plugin.importedState": true,
    "plugin.disable_full_page_plugin_for_types": "application/pdf",
    "print.printer_\\\\vprint03.init.de\\2.OG_-_Phaser_7500DT.print_edge_top": 0,
    "print.printer_\\\\vprint03.init.de\\2.OG_-_Phaser_7500DT.print_paper_data": 9,
    "print.printer_\\\\vprint03.init.de\\2.OG_-_Phaser_7500DT.print_footercenter": "",
    "print.printer_\\\\vprint03.init.de\\2.OG_-_Phaser_7500DT.print_edge_right": 0,
    "print.printer_\\\\vprint03.init.de\\2.OG_-_Phaser_7500DT.print_footerright": "&D",
    "print.printer_\\\\vprint03.init.de\\2.OG_-_Phaser_7500DT.print_headercenter": "",
    "print.printer_\\\\vprint03.init.de\\2.OG_-_Phaser_7500DT.print_unwriteable_margin_left": 0,
    "print.printer_\\\\vprint03.init.de\\2.OG_-_Phaser_7500DT.print_in_color": true,
    "print.printer_\\\\vprint03.init.de\\2.OG_-_Phaser_7500DT.print_unwriteable_margin_top": 0,
    "print.printer_\\\\vprint03.init.de\\2.OG_-_Phaser_7500DT.print_footerleft": "&PT",
    "print.printer_\\\\vprint03.init.de\\2.OG_-_Phaser_7500DT.print_evenpages": true,
    "print.printer_\\\\vprint03.init.de\\2.OG_-_Phaser_7500DT.print_bgcolor": false,
    "print.printer_\\\\vprint03.init.de\\2.OG_-_Phaser_7500DT.print_to_file": false,
    "print.printer_\\\\vprint03.init.de\\2.OG_-_Phaser_7500DT.print_margin_left": "0.5",
    "print.printer_\\\\vprint03.init.de\\2.OG_-_Phaser_7500DT.print_edge_bottom": 0,
    "print.printer_\\\\vprint03.init.de\\2.OG_-_Phaser_7500DT.print_reversed": false,
    "print.printer_\\\\vprint03.init.de\\2.OG_-_Phaser_7500DT.print_duplex": -437918235,
    "print.printer_\\\\vprint03.init.de\\2.OG_-_Phaser_7500DT.print_page_delay": 50,
    "print.printer_\\\\vprint03.init.de\\2.OG_-_Phaser_7500DT.print_paper_name": "",
    "print.printer_\\\\vprint03.init.de\\2.OG_-_Phaser_7500DT.print_headerright": "&U",
    "print.printer_\\\\vprint03.init.de\\2.OG_-_Phaser_7500DT.print_paper_width": " -1,00",
    "print.printer_\\\\vprint03.init.de\\2.OG_-_Phaser_7500DT.print_shrink_to_fit": true,
    "print.printer_\\\\vprint03.init.de\\2.OG_-_Phaser_7500DT.print_unwriteable_margin_bottom": 0,
    "print.printer_\\\\vprint03.init.de\\2.OG_-_Phaser_7500DT.print_margin_right": "0.5",
    "print.printer_\\\\vprint03.init.de\\2.OG_-_Phaser_7500DT.print_unwriteable_margin_right": 0,
    "print.printer_\\\\vprint03.init.de\\2.OG_-_Phaser_7500DT.print_paper_size_unit": 1,
    "print.printer_\\\\vprint03.init.de\\2.OG_-_Phaser_7500DT.print_margin_top": "0.5",
    "print.printer_\\\\vprint03.init.de\\2.OG_-_Phaser_7500DT.print_orientation": 0,
    "print.printer_\\\\vprint03.init.de\\2.OG_-_Phaser_7500DT.print_margin_bottom": "0.5",
    "print.printer_\\\\vprint03.init.de\\2.OG_-_Phaser_7500DT.print_resolution": 600,
    "print.printer_\\\\vprint03.init.de\\2.OG_-_Phaser_7500DT.print_headerleft": "&T",
    "print.printer_\\\\vprint03.init.de\\2.OG_-_Phaser_7500DT.print_oddpages": true,
    "print.printer_\\\\vprint03.init.de\\2.OG_-_Phaser_7500DT.print_paper_height": " -1,00",
    "print.printer_\\\\vprint03.init.de\\2.OG_-_Phaser_7500DT.print_bgimages": false,
    "print.printer_\\\\vprint03.init.de\\2.OG_-_Phaser_7500DT.print_edge_left": 0,
    "print.printer_\\\\vprint03.init.de\\2.OG_-_Phaser_7500DT.print_scaling": "  1,00",
    "security.sandbox.content.tempDirSuffix": "{d82f65c3-d1d6-498f-a9aa-0a76e6775a3f}",
    "security.disable_button.openCertManager": false,
    "services.sync.declinedEngines": "adblockplus,prefs,addons,tabs,bookmarks,forms,history",
    "services.sync.lastPing": 1473327436,
    "services.sync.lastSync": "Thu Sep 08 2016 13:18:20 GMT+0200",
    "services.sync.numClients": 6,
    "services.sync.engine.tabs": false,
    "services.sync.engine.prefs": false,
    "services.sync.engine.bookmarks": false,
    "services.sync.engine.history": false,
    "services.sync.engine.addons": false,
    "services.sync.engine.prefs.modified": false,
    "storage.vacuum.last.places.sqlite": 1471244537,
    "storage.vacuum.last.index": 2,
    "ui.osk.debug.keyboardDisplayReason": "IKPOS: Touch screen not found."
  },
  "lockedPreferences": {},
  "javaScript": {
    "incrementalGCEnabled": true
  },
  "accessibility": {
    "isActive": false,
    "forceDisabled": 0
  },
  "libraryVersions": {
    "NSPR": {
      "minVersion": "4.12",
      "version": "4.12"
    },
    "NSS": {
      "minVersion": "3.26",
      "version": "3.26"
    },
    "NSSUTIL": {
      "minVersion": "3.26",
      "version": "3.26"
    },
    "NSSSSL": {
      "minVersion": "3.26",
      "version": "3.26"
    },
    "NSSSMIME": {
      "minVersion": "3.26",
      "version": "3.26"
    }
  },
  "userJS": {
    "exists": true
  },
  "crashes": {
    "submitted": [],
    "pending": 3
  },
  "sandbox": {
    "contentSandboxLevel": 1
  },
  "extensions": [
    {
      "name": "Adblock Plus",
      "version": "2.7.3",
      "isActive": true,
      "id": "{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}"
    },
    {
      "name": "Add to Wunderlist",
      "version": "3.1.1",
      "isActive": true,
      "id": "jid1-3gu11JeYBiIuJA@jetpack"
    },
    {
      "name": "Add-on Compatibility Reporter",
      "version": "2.2.0",
      "isActive": true,
      "id": "compatibility@addons.mozilla.org"
    },
    {
      "name": "Brief",
      "version": "2.2.2",
      "isActive": true,
      "id": "brief@mozdev.org"
    },
    {
      "name": "CheckFox",
      "version": "0.9.2.1-signed.1-signed",
      "isActive": true,
      "id": "{BAEC7B80-9A31-47b2-A68B-DCAC8DF48E87}"
    },
    {
      "name": "Empty Cache Button",
      "version": "2.7.1-signed.1-signed",
      "isActive": true,
      "id": "{4cc4a13b-94a6-7568-370d-5f9de54a9c7f}"
    },
    {
      "name": "FlyWeb",
      "version": "1.0.0",
      "isActive": true,
      "id": "flyweb@mozilla.org"
    },
    {
      "name": "Form History Control",
      "version": "1.4.0.6",
      "isActive": true,
      "id": "formhistory@yahoo.com"
    },
    {
      "name": "FoxReplace",
      "version": "0.17.1.1-signed.1-let-fixed",
      "isActive": true,
      "id": "fox@replace.fx"
    },
    {
      "name": "Hacker News Feed",
      "version": "0.6.1",
      "isActive": true,
      "id": "jid1-JAKHAfLpsTwcIg@jetpack"
    },
    {
      "name": "JSONView",
      "version": "1.1.1",
      "isActive": true,
      "id": "jsonview@brh.numbera.com"
    },
    {
      "name": "LiveReload",
      "version": "2.1.1",
      "isActive": true,
      "id": "livereload@livereload.com"
    },
    {
      "name": "Multi-process staged rollout",
      "version": "1.2",
      "isActive": true,
      "id": "e10srollout@mozilla.org"
    },
    {
      "name": "Pixel Perfect",
      "version": "2.0.14",
      "isActive": true,
      "id": "pixelperfectplugin@openhouseconcepts.com"
    },
    {
      "name": "Pocket",
      "version": "1.0.4",
      "isActive": true,
      "id": "firefox@getpocket.com"
    },
    {
      "name": "Print Edit",
      "version": "17.2",
      "isActive": true,
      "id": "printedit@DW-dev"
    },
    {
      "name": "Saved Password Editor",
      "version": "2.10",
      "isActive": true,
      "id": "savedpasswordeditor@daniel.dawson"
    },
    {
      "name": "ScrapBook",
      "version": "1.5.14",
      "isActive": true,
      "id": "{53A03D43-5363-4669-8190-99061B2DEBA5}"
    },
    {
      "name": "Tab Mix Plus",
      "version": "0.5.0.0",
      "isActive": true,
      "id": "{dc572301-7619-498c-a57d-39143191b318}"
    },
    {
      "name": "Textarea Cache",
      "version": "0.9.3.4",
      "isActive": true,
      "id": "{578e7caa-210f-4967-a0d3-88fe5b59a39f}"
    },
    {
      "name": "The easiest Xdebug",
      "version": "2.1.1-signed.1-signed",
      "isActive": true,
      "id": "jid1-fQpPMP6uBdJNCg@jetpack"
    },
    {
      "name": "uBlock Origin",
      "version": "1.9.4",
      "isActive": true,
      "id": "uBlock0@raymondhill.net"
    },
    {
      "name": "Web Compat",
      "version": "1.0",
      "isActive": true,
      "id": "webcompat@mozilla.org"
    },
    {
      "name": "DevTools Prototyper",
      "version": "4.1.1",
      "isActive": false,
      "id": "devtools-prototyper@tim-addons.com"
    },
    {
      "name": "FireQuery",
      "version": "2.0.4",
      "isActive": false,
      "id": "firequery@binaryage.com"
    }
  ],
  "experiments": [],
  "graphics": {
    "numTotalWindows": 1,
    "numAcceleratedWindows": 1,
    "windowLayerManagerType": "Direct3D 11",
    "windowLayerManagerRemote": true,
    "supportsHardwareH264": "Yes; Using D3D11 API",
    "currentAudioBackend": "wasapi",
    "adapterDescription": "AMD Radeon HD 7000 series",
    "adapterVendorID": "0x1002",
    "adapterDeviceID": "0x6778",
    "adapterSubsysID": "21201028",
    "adapterRAM": "1024",
    "adapterDrivers": "aticfx64 aticfx64 aticfx64 aticfx32 aticfx32 aticfx32 atiumd64 atidxx64 atidxx64 atiumdag atidxx32 atidxx32 atiumdva atiumd6a atitmm64",
    "driverVersion": "13.251.9001.1001",
    "driverDate": "7-4-2014",
    "adapterDescription2": "",
    "adapterVendorID2": "",
    "adapterDeviceID2": "",
    "adapterSubsysID2": "",
    "adapterRAM2": "",
    "adapterDrivers2": "",
    "driverVersion2": "",
    "driverDate2": "",
    "isGPU2Active": false,
    "direct2DEnabled": true,
    "directWriteEnabled": true,
    "directWriteVersion": "6.3.9600.18123",
    "webglRenderer": "Google Inc. -- ANGLE (AMD Radeon HD 7000 series Direct3D11 vs_5_0 ps_5_0)",
    "webgl2Renderer": "(no info)",
    "info": {
      "AzureCanvasBackend": "direct2d 1.1",
      "AzureCanvasAccelerated": 0,
      "AzureFallbackCanvasBackend": "cairo",
      "AzureContentBackend": "direct2d 1.1",
      "ApzWheelInput": 1,
      "ApzTouchInput": 1
    },
    "featureLog": {
      "features": [
        {
          "name": "HW_COMPOSITING",
          "description": "Compositing",
          "status": "available",
          "log": [
            {
              "type": "default",
              "status": "available"
            }
          ]
        },
        {
          "name": "D3D11_COMPOSITING",
          "description": "Direct3D11 Compositing",
          "status": "available",
          "log": [
            {
              "type": "default",
              "status": "available"
            }
          ]
        },
        {
          "name": "D3D9_COMPOSITING",
          "description": "Direct3D9 Compositing",
          "status": "available",
          "log": [
            {
              "type": "default",
              "status": "available"
            }
          ]
        },
        {
          "name": "DIRECT2D",
          "description": "Direct2D",
          "status": "available",
          "log": [
            {
              "type": "default",
              "status": "available"
            }
          ]
        },
        {
          "name": "D3D11_HW_ANGLE",
          "description": "Direct3D11 hardware ANGLE",
          "status": "available",
          "log": [
            {
              "type": "default",
              "status": "available"
            }
          ]
        }
      ],
      "fallbacks": []
    },
    "crashGuards": []
  }
}
```

### PR DESCRIPTION
**Pull request by wagnerand**
Fixes #61.

### CODE REVIEW

File: lib/main.js [hunk 1]
```diff
@@ -256,13 +256,19 @@ function retrieveAddonIcon(addon, callback) {
         var xhr = new XMLHttpRequest();
         xhr.onreadystatechange = function () {
             if (this.readyState === 4) {
-            addon.icon = 'data:image/png;base64,' + base64.encode(String.fromCharCode.apply(null, new Uint8Array(this.response)));
-            callback(addon);
+                addon.icon = 'data:image/png;base64,' + base64.encode(String.fromCharCode.apply(null, new Uint8Array(this.response)));
+                callback(addon);
```
Comment (wagnerand) [inline lib/main.js]: Unrelated, but whatevs.

**Comment by tofumatt** [comment]
r+

**Comment by wagnerand** [comment]
Thank you for the fast review!
